/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Controlador.ControlVistaPrincipalCliente;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JORGE
 */
public class VistaPrincipalClientePlus extends javax.swing.JFrame {

    ControlVistaPrincipalCliente controlVPC = new ControlVistaPrincipalCliente();
    int idCliente;
    /**
     * Creates new form VistaPrincipalClientePlus
     */
    public VistaPrincipalClientePlus(int idCliente) {
        initComponents();
        setLocationRelativeTo(this);
        this.idCliente = idCliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGestionPrestamos = new javax.swing.JButton();
        txtMisPrestamos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtGestionPrestamos.setBackground(new java.awt.Color(153, 153, 255));
        txtGestionPrestamos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGestionPrestamos.setText("Gestion de prestamos");
        txtGestionPrestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGestionPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGestionPrestamosActionPerformed(evt);
            }
        });

        txtMisPrestamos.setBackground(new java.awt.Color(153, 153, 255));
        txtMisPrestamos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMisPrestamos.setText("Msi prestamos");
        txtMisPrestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtMisPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMisPrestamosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Vista Cliente");

        btnRegresar1.setBackground(new java.awt.Color(153, 153, 255));
        btnRegresar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar1.setText("Cerrar secion");
        btnRegresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGestionPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMisPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(121, 121, 121)
                .addComponent(txtGestionPrestamos)
                .addGap(18, 18, 18)
                .addComponent(txtMisPrestamos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(btnRegresar1)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGestionPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGestionPrestamosActionPerformed
        // TODO add your handling code here:
        VistaPrestamosClientePlus vistaPC;
        try {
            vistaPC = new VistaPrestamosClientePlus(idCliente);
            vistaPC.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(VistaPrincipalClientePlus.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_txtGestionPrestamosActionPerformed

    private void txtMisPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMisPrestamosActionPerformed
        // TODO add your handling code here:
        try {
            VistaMisPrestamosClientePlus vistaMP = new VistaMisPrestamosClientePlus(idCliente);
            vistaMP.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(VistaPrincipalClientePlus.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtMisPrestamosActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
        VistaLoginPlus vistaL = new VistaLoginPlus();
        vistaL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton txtGestionPrestamos;
    private javax.swing.JButton txtMisPrestamos;
    // End of variables declaration//GEN-END:variables
}
