/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Controlador.ControlVistaAgregarLibrosAdmin;
import Controlador.ControlVistaGestionLibrosAdmin;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Libro;

/**
 *
 * @author JORGE
 */
public class VistaGestionLibrosAdminPlus extends javax.swing.JFrame {

    ControlVistaGestionLibrosAdmin controlVGLA;
    ArrayList<Libro> libros;

    /**
     * Creates new form VistaGestionLibrosAdmin
     */
    public VistaGestionLibrosAdminPlus() throws SQLException {
        initComponents();
        setLocationRelativeTo(this);
        controlVGLA = new ControlVistaGestionLibrosAdmin();
        libros = controlVGLA.getLibros();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibro = new javax.swing.JTable();
        btnRegresar1 = new javax.swing.JButton();
        btnAgregarLibro = new javax.swing.JButton();
        btnEditarLibro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Autor", "Isbn", "Editorial", "Npaginas", "Disponibilidad", "Genero"
            }
        ));
        jScrollPane1.setViewportView(tablaLibro);

        btnRegresar1.setBackground(new java.awt.Color(153, 153, 255));
        btnRegresar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar1.setText("Regresar");
        btnRegresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        btnAgregarLibro.setBackground(new java.awt.Color(153, 153, 255));
        btnAgregarLibro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregarLibro.setText("Agregar Libro");
        btnAgregarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });

        btnEditarLibro.setBackground(new java.awt.Color(153, 153, 255));
        btnEditarLibro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditarLibro.setText("Editar Libro");
        btnEditarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLibroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Gestion Libros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(314, 314, 314)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEditarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 337, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(btnEditarLibro)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarLibro)
                .addGap(24, 24, 24)
                .addComponent(btnRegresar1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
        VistaPrincipalAdmiPlus vistaPA = new VistaPrincipalAdmiPlus();
        vistaPA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        // TODO add your handling code here:
        VistaAgregarLibrosAdminPlus vistAL = new VistaAgregarLibrosAdminPlus();
        vistAL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    private void btnEditarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarLibroActionPerformed

    private void llenarTabla() {
        DefaultTableModel model = new DefaultTableModel(new String[]{"Id", "Nombre", "Autor", "Isbn", "Editorial", "Npaginas", "Disponibilidad", "Genero"},
                libros.size());
        tablaLibro.setModel(model);
        TableModel modelP = tablaLibro.getModel();
        for (int i = 0; i < libros.size(); i++) {
            Libro libro = libros.get(i);
            modelP.setValueAt(libro.getId(), i, 0);
            modelP.setValueAt(libro.getNombre(), i, 1);
            modelP.setValueAt(libro.getAutor(), i, 2);
            modelP.setValueAt(libro.getIsbn(), i, 3);
            modelP.setValueAt(libro.getEditorial(), i, 4);
            modelP.setValueAt(libro.getNpaginas(), i, 5);
            modelP.setValueAt(libro.getDisponibilidad(), i, 6);
            modelP.setValueAt(libro.getGenero(), i, 7);
        }
    }

  
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnEditarLibro;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaLibro;
    // End of variables declaration//GEN-END:variables

}
