/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Controlador.ControlVistaPrestamoCliente;
import excepciones.InvalidUserDataException;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Libro;
import modelo.Prestamo;

/**
 *
 * @author JORGE
 */
public class VistaPrestamosClientePlus extends javax.swing.JFrame {

    ControlVistaPrestamoCliente controlVPC;
    ArrayList<Libro> libros;
    Date fechaPrestamo;
    Date fechaDevolucion;
    String nombreRaiz;
    int idCliente;

    /**
     * Creates new form VistaPrestamosClientePlus
     */
    public VistaPrestamosClientePlus(int idCliente) throws SQLException {
        initComponents();
        setLocationRelativeTo(this);
        controlVPC = new ControlVistaPrestamoCliente(idCliente);
        libros = controlVPC.getLibros();
        llenarTabla();
        agregarListenerTabla();
        this.idCliente = idCliente;
        lblFechaPrestamo.setText("Fecha prestamo: " + LocalDate.now());
        lblFechaDevolucion.setText("Fecha prestamo: " + LocalDate.now().plusDays(3));
        fechaPrestamo = (Date.valueOf(LocalDate.now()));
        fechaDevolucion = (Date.valueOf(LocalDate.now().plusDays(3)));
        nombreRaiz = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        txtIsbn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnPrestar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibro = new javax.swing.JTable();
        lblFechaPrestamo = new javax.swing.JLabel();
        lblFechaDevolucion = new javax.swing.JLabel();
        btnRecomendacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegresar.setBackground(new java.awt.Color(153, 153, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Isbn");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Gestion Prestamos");

        btnPrestar.setBackground(new java.awt.Color(153, 153, 255));
        btnPrestar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrestar.setText("Prestar");
        btnPrestar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        tablaLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Autor", "Isbn", "Editorial", "Npaginas", "Disponibilidad", "Genero"
            }
        ));
        jScrollPane1.setViewportView(tablaLibro);

        lblFechaPrestamo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaPrestamo.setText("fecha prestamo:");

        lblFechaDevolucion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaDevolucion.setText("fecha devolucion:");

        btnRecomendacion.setBackground(new java.awt.Color(153, 153, 255));
        btnRecomendacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRecomendacion.setText("Obtener recomendacion");
        btnRecomendacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecomendacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecomendacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRecomendacion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(63, 63, 63)
                                .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFechaPrestamo))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFechaDevolucion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnRecomendacion)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnPrestar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaPrestamo)
                    .addComponent(btnRegresar)
                    .addComponent(lblFechaDevolucion))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VistaPrincipalClientePlus vistaPC = new VistaPrincipalClientePlus(idCliente);
        vistaPC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = nombreRaiz;
            String isbn = txtIsbn.getText();
            Prestamo prestamo = new Prestamo(idCliente, nombre, isbn, fechaPrestamo, fechaDevolucion);
            controlVPC.registrarPrestamo(prestamo);
            JOptionPane.showMessageDialog(null, "El prestamo fue hecho con exito");
            txtIsbn.setText("");
            nombreRaiz = "";
        } catch (InvalidUserDataException ex) {
            Logger.getLogger(VistaPrestamosClientePlus.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VistaPrestamosClientePlus.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnRecomendacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecomendacionActionPerformed
        // TODO add your handling code here:
        String peticion1 = "nesesito una recomendacion de un  libro basado en los libros que ha "
                + "leido el usuario estos son los libros de la biblioteca : ";
        for (int i = 0; i < libros.size(); i++) {
            peticion1 = peticion1 + libros.get(i) + "\n";
        }
        peticion1 = peticion1 + "y estos son los prestamos que ha hecho el usuario:";
        for (int i = 0; i < controlVPC.getPrestamos().size(); i++) {
            peticion1 = peticion1 + controlVPC.getPrestamos().get(i) + "\n";
        }
        peticion1 = peticion1 + "si no huviera ningun prestamo recomendar un libro aleatorio ";
        String pront = controlVPC.createContent(peticion1);
//        JOptionPane.showMessageDialog(null, pront);
        VistaRecomendacion vistaR = new VistaRecomendacion(pront, idCliente);
        vistaR.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_btnRecomendacionActionPerformed

    private void llenarTabla() {
        DefaultTableModel model = new DefaultTableModel(new String[]{"Id", "Nombre", "Autor", "Isbn", "Editorial", "Npaginas", "Disponibilidad", "Genero"},
                libros.size());
        tablaLibro.setModel(model);
        TableModel modelP = tablaLibro.getModel();
        for (int i = 0; i < libros.size(); i++) {
            Libro libro = libros.get(i);
            modelP.setValueAt(libro.getId(), i, 0);
            modelP.setValueAt(libro.getNombre(), i, 1);
            modelP.setValueAt(libro.getAutor(), i, 2);
            modelP.setValueAt(libro.getIsbn(), i, 3);
            modelP.setValueAt(libro.getEditorial(), i, 4);
            modelP.setValueAt(libro.getNpaginas(), i, 5);
            modelP.setValueAt(libro.getDisponibilidad(), i, 6);
            modelP.setValueAt(libro.getGenero(), i, 7);

        }
    }

    private void agregarListenerTabla() {
        ListSelectionModel model = tablaLibro.getSelectionModel();
        model.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = tablaLibro.getSelectedRow();
                    if (selectedRow != -1) {
                        // Obtén el valor de la columna "№ Plaza"
                        String nombreLibro = (String) tablaLibro.getValueAt(selectedRow, 1);
                        String isbn = (String) tablaLibro.getValueAt(selectedRow, 3);
                        txtIsbn.setText(isbn);
                        nombreRaiz = nombreLibro;
                    }
                }
            }
        });
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnRecomendacion;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaDevolucion;
    private javax.swing.JLabel lblFechaPrestamo;
    private javax.swing.JTable tablaLibro;
    private javax.swing.JTextField txtIsbn;
    // End of variables declaration//GEN-END:variables
}
